# Generated by Django 4.2 on 2023-04-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voxpop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="admin_group",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="hostname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="idp",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
