# Generated by Django 4.1.7 on 2023-03-22 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voxpop", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="pub_data",
            new_name="pub_date",
        ),
    ]
