# Generated by Django 4.2 on 2023-04-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("voxpop", "0002_alter_organisation_admin_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="voxpop.question",
            ),
        ),
    ]
