# Generated by Django 4.2 on 2023-09-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voxpop", "0006_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="channel_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
