# Generated by Django 4.2.6 on 2023-10-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voxpop", "0007_message_channel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voxpop",
            name="allow_anonymous",
            field=models.BooleanField(default=True, verbose_name="allow anonymous"),
        ),
    ]
