# Generated by Django 4.1.7 on 2023-03-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='vote_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
